---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enableTutorial

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: CP_String
          operator: regex
          operands:
            - hello
    flagValue: false
