---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enableTutorial

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - property:
          name: GregDelete
          operator: is-true
    flagValue: true
  - allOf:
      - property:
          name: CP_String
          operator: in-array
          operands:
            - ' hello'
    flagValue: false
