---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: titleColors

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: Blue

conditions:
  - allOf:
      - anyOf:
          - group:
              name: parent
    flagValue: Blue
