---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: titleColors

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.now2
          operator: after
          operands:
            - "2025-03-21T04:00:00.000Z"
    flagValue: Blue
