---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enableTutorial

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 0
    from: 2025-03-21T13:45:00Z
  - percentage: 100
    from: 2025-03-21T13:50:00Z

conditions: []
