---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: enableTutorial

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  - percentage: 20
    option: true
  - percentage: 80
    option: false

conditions: []
