apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: rw with io 2
on:
  workflow_call:
    outputs:
      out1:
        value: ${{ jobs.build.outputs.output1 }}
        description: Output desc 1
      out2:
        value: ${{ jobs.build.outputs.output2 }}
        description: Output desc 2
    inputs:
      mystring:
        type: string
        required: false
      mynumber:
        type: number
        required: false
      mybool:
        type: boolean
        required: false
      mychoice:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: false
  workflow_dispatch:
    inputs:
      mystring:
        type: string
        default: test
      mynumber:
        type: number
        default: 1
      mybool:
        type: boolean
        default: false
      mychoice:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt1
jobs:
  buildserv:
    services:
      redis:
        image: redis:7-alpine3.20
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
    needs:
      - noapproval
  build:
    outputs:
      output1: this is output1
      output2: this is output2
    steps:
      - name: Print param and return outputs
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Params received: ${{ inputs.mystring }} ${{ inputs.mynumber }} ${{ inputs.mybool }} ${{ inputs.mychoice }} "
    needs:
      - approve
  approve:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 4b7f53fc-d4fe-11ec-bb55-42010a83ae55
      disallowLaunchByUser: false
      instructions: ""
  noapproval:
    environment: ""
    steps:
      - name: sdafsdf
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello there"
  noapproval2:
    environment: ""
    steps:
      - name: sdafsdf
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello there"
  noapproval3:
    environment: ""
    steps:
      - name: sdafsdf
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello there"
  buildserv2:
    services:
      redis:
        image: redis:7-alpine3.20
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
    needs:
      - noapproval
  buildserv3:
    services:
      redis:
        image: redis:7-alpine3.20
    steps:
      - uses: docker://redis:7-alpine3.20
        name: Run Redis commands
        run: |
          redis-cli SET testkey "Hello Redis!"
          redis-cli GET testkey
    needs:
      - noapproval2